# Data Manipulation

```{r, cache = TRUE}
library(tidyverse)
library(tidymodels)
library(janitor)
```

## Read in Data

```{r, cache=TRUE, cache = TRUE}
read_csv("data_sources/Batting.csv")
```

### Fix Read In Errors {-}

```{r, cache = TRUE}
read_csv("data_sources/Batting.csv", col_types = cols(SF = col_double(), GIDP = col_double()))
```

```{r, cache = TRUE}
read_csv("data_sources/Batting.csv", guess_max = 10000)
```

### Clean Column Names {-}

```{r, cache = TRUE}
read_csv("data_sources/Batting.csv", col_types = cols(SF = col_double(), GIDP = col_double())) %>% 
  clean_names()
```

## Analysis with `dplyr`

Who has the highest career slugging percentage?

### Select {-}

```{r, cache = TRUE}
data = read_csv("data_sources/Batting.csv", col_types = cols(SF = col_double(), GIDP = col_double())) %>% 
  clean_names()
```


```{r, cache = TRUE}
data %>% 
  select(player_id,year_id,h,x2b,x3b,hr,ab, g)
```

### Group_by {-}

```{r, cache = TRUE}
data %>% 
  select(player_id,year_id,h,x2b,x3b,hr,ab, g) %>% 
  group_by(player_id)
```

### Summarise {-}

```{r, cache = TRUE}
data %>% 
  select(player_id,year_id,h,x2b,x3b,hr,ab, g) %>% 
  group_by(player_id) %>% 
  summarise(h = sum(h),
            x2b = sum(x2b),
            x3b = sum(x3b),
            hr = sum(hr),
            ab = sum(ab),
            g = sum(g))
```

### Filter {-}

```{r, cache = TRUE}
data %>% 
  select(player_id,year_id,h,x2b,x3b,hr,ab, g) %>% 
  group_by(player_id) %>% 
  summarise(h = sum(h), 
            x2b = sum(x2b),
            x3b = sum(x3b),
            hr = sum(hr),
            ab = sum(ab),
            g = sum(g)) %>% 
  filter(g>1000) 
```

### Mutate {-}

```{r, cache = TRUE}
data %>% 
  select(player_id,year_id,h,x2b,x3b,hr,ab, g) %>% 
  group_by(player_id) %>% 
  summarise(h = sum(h), 
            x2b = sum(x2b),
            x3b = sum(x3b),
            hr = sum(hr),
            ab = sum(ab),
            g = sum(g)) %>% 
  filter(g>1000) %>% 
  mutate(slg = (h + x2b + 2*x3b + 3*hr)/ab)
```

### Arrange {-}

```{r, cache = TRUE}
slgdata = 
data %>% 
  select(player_id,year_id,h,x2b,x3b,hr,ab, g) %>% 
  group_by(player_id) %>% 
  summarise(h = sum(h), 
            x2b = sum(x2b),
            x3b = sum(x3b),
            hr = sum(hr),
            ab = sum(ab),
            g = sum(g)) %>% 
  filter(g>1000) %>% 
  mutate(slg = (h + x2b + 2*x3b + 3*hr)/ab) %>% 
  arrange(desc(slg))

slgdata
```

## Joins

### Player ID Data {-}

```{r, cache = TRUE}
read_csv("data_sources/Master.csv") 
```

```{r, cache = TRUE}
read_csv("data_sources/Master.csv") %>% 
  select(playerID, nameFirst, nameLast) %>% 
  mutate(player = paste(nameFirst,nameLast)) %>% 
  select(-starts_with("name"))
```


```{r, cache = TRUE}
master = 
read_csv("data_sources/Master.csv") %>% 
  select(playerID, nameFirst, nameLast) %>% 
  mutate(player = paste(nameFirst,nameLast)) %>% 
  select(-starts_with("name"))
```

### Join the Data {-}

```{r, cache = TRUE}
slgdata %>% 
  left_join(master, by = c("player_id" = "playerID"))
```

```{r, cache = TRUE}
slgname = 
slgdata %>% 
  left_join(master, by = c("player_id" = "playerID"))
```

### Rename Columns {-}

```{r, cache = TRUE}
slgname %>% 
  rename(doubles = x2b, triples = x3b)
```


```{r, cache = TRUE}
slgname = 
slgname %>% 
  rename(doubles = x2b, triples = x3b)
```

### Reorder Columns {-}

```{r, cache = TRUE}
slgname %>% 
  select(player_id, player, everything())
```

```{r, cache = TRUE}
slgname =
slgname %>% 
  select(player_id, player, everything())
```


## Other dplyr Tricks

### Count {-}

```{r, cache = TRUE}
data
```

```{r, cache = TRUE}
data %>% 
  count(player_id)
```

```{r, cache = TRUE}
data %>% 
  count(player_id, sort = TRUE)
```

### Uncount {-}

```{r, cache = TRUE}
slgname %>% 
  uncount(triples)
```

### Summarise {-}

```{r, cache = TRUE}
data %>% 
  select(player_id,year_id,h,x2b,x3b,hr,ab, g) %>% 
  group_by(player_id) %>% 
  summarise(h = sum(h), 
            x2b = sum(x2b),
            x3b = sum(x3b),
            hr = sum(hr),
            ab = sum(ab),
            g = sum(g)) 
```


```{r, cache = TRUE}
data %>% 
  select(player_id,year_id,h,x2b,x3b,hr,ab, g) %>% 
  group_by(player_id) %>% 
  summarise_at(vars(-year_id),~sum(.))
```
