# Data Visualization

## Bar Chart

```{r}
slgname
```

### Canvas {-}

```{r}
slgname %>% 
  ggplot()
```

### Mapping {-}

```{r}
slgname %>% 
  ggplot(aes(x=player, y = hr))
```

### Filter Data {-}

```{r}
slgname %>% 
  top_n(20, h) %>% 
  ggplot(aes(x=player, y = hr)) 
```

### Plot 'mechanism' {-}

```{r}
slgname %>% 
  top_n(20, h) %>% 
  ggplot(aes(x=player, y = hr)) +
  geom_col()
```

### Coordinate Flip {-}

```{r}
slgname %>% 
  top_n(20, h) %>% 
  ggplot(aes(x=player, y = hr)) +
  geom_col() +
  coord_flip()
```

### Reorder Factors {-}

```{r}
slgname %>% 
  top_n(20, h) %>% 
  ggplot(aes(x=fct_reorder(player,hr), y = hr)) +
  geom_col() +
  coord_flip()
```

### Color Bars {-}

```{r}
slgname %>% 
  top_n(20, h) %>% 
  ggplot(aes(x=fct_reorder(player,hr), y = hr, fill = slg)) +
  geom_col() +
  coord_flip()
```

### Update Labels {-}

```{r}
slgname %>% 
  top_n(20, h) %>% 
  ggplot(aes(x=fct_reorder(player,hr), y = hr, fill = slg)) +
  geom_col() +
  coord_flip() +
  labs(x = "Player", y = "Home Runs", 
       title = "Top 20 Home Run Hitters", 
       fill = "Slugging Percentage",
       subtitle = "1871-2016", 
       caption = "*Among Players Who've Played at least 1000 games")
```

## Scatter Plot {-}

```{r}
scatterdat = 
data %>% 
  filter(lg_id == "AL") %>% 
  mutate(team_id = fct_lump(team_id, n = 12)) %>% 
  filter(team_id != "Other") %>% 
  filter(complete.cases(.)) %>%
  filter(year_id>1990) %>% 
  group_by(team_id,year_id) %>% 
  summarise_at(vars(g:gidp), ~sum(.))  

scatterdat
```

### Canvas {-}

```{r}
scatterdat %>% 
  ggplot() 
```

### Mapping {-}

```{r}
scatterdat %>% 
  ggplot(aes(x=year_id,y=hr,color = fct_reorder(team_id,-hr)))
```

### Plot 'mechanism': geom_point() {-}

```{r}
scatterdat %>% 
  ggplot(aes(x=year_id,y=hr,color = fct_reorder(team_id,-hr))) +
  geom_point() 
```

### Plot 'mechanism': geom_smooth() {-}

```{r}
scatterdat %>% 
  ggplot(aes(x=year_id,y=hr)) +
  geom_point(aes(color = fct_reorder(team_id,-hr))) +
  geom_smooth()
```

### Facet Plots {-}

```{r}
scatterdat %>% 
  ggplot(aes(x=year_id,y=hr)) +
  geom_point(aes(color = fct_reorder(team_id,-hr))) +
  geom_smooth() +
  facet_wrap(~team_id)
```

### Update Labels {-}

```{r}
scatterdat %>% 
  ggplot(aes(x=year_id,y=hr)) +
  geom_point(aes(color = fct_reorder(team_id,-hr))) +
  geom_smooth() +
  facet_wrap(~team_id) +
  labs(title = "Home Run Changes Over Time",
       subtitle = paste("From", min(scatterdat$year_id), "to", max(scatterdat$year_id)),
       color = "Team",
       x = "Season", y = "Season Home Run Total")
```

### Change Smoothing Line {-}

```{r}
scatterdat %>% 
  ggplot(aes(x=year_id,y=hr)) +
  geom_point(aes(color = fct_reorder(team_id,-hr))) +
  geom_smooth(method = "lm") +
  facet_wrap(~team_id) +
  labs(title = "Home Run Changes Over Time",
       subtitle = paste("From", min(scatterdat$year_id), "to", max(scatterdat$year_id)),
       color = "Team",
       x = "Season", y = "Season Home Run Total")
```

## Animation

```{r echo=TRUE, message=FALSE, warning=FALSE}
library(gganimate)

animdata =
  data %>%
  filter(!is.na(lg_id)) %>%
  group_by(year_id, team_id) %>%
  summarise_at(vars(hr, so, bb, ab), ~ sum(., na.rm = TRUE)) %>%
  ungroup() %>%
  inner_join(data %>%
               select(year_id, team_id, lg_id) %>%
               distinct()) 

animdata
```


```{r}
p = animdata %>% 
  ggplot(aes(x = so,y = hr, color = bb,size = ab,group = year_id)) +
  geom_point() +
  facet_wrap(~ lg_id) +
  transition_states(year_id,transition_length = 1,state_length = 30) +
  labs(title = 'Year: {closest_state}') +
  enter_fade() +
  exit_fade()

animate(p,nframes = length(unique(data$year_id)) * 2)
```



<!-- ```{r} -->
<!-- library(gapminder) -->

<!-- ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, colour = country)) + -->
<!--   geom_point(alpha = 0.7, show.legend = FALSE) + -->
<!--   scale_colour_manual(values = country_colors) + -->
<!--   scale_size(range = c(2, 12)) + -->
<!--   scale_x_log10() + -->
<!--   facet_wrap(~continent) + -->
<!--   # Here comes the gganimate specific bits -->
<!--   labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy') + -->
<!--   transition_time(year) + -->
<!--   ease_aes('linear') -->

<!-- # file_renderer(dir = ".", prefix = "gganim_plot", overwrite = FALSE) -->
<!-- ``` -->

